from __future__ import annotations

"""Build Document -> Section -> Sentence hierarchy graphs with optional concept nodes.

Dependencies:
    pip install torch

Input:
    sentence-level CONCH embeddings plus metadata generated by
    encode_sentence_exports_conch.py

Output:
    One .pt file per document with graph tensors and one companion .json file
    with human-readable node/edge metadata.

Graph design:
    - Base node levels: Document, Section, Sentence
    - Optional concept level: Concept
    - Base edge types: parent, next
    - Optional concept edge types: mention, ontology, same_sentence, same_section
    - Sentence features: original CONCH embeddings
    - Section features: mean pooling over child sentences
    - Document feature: mean pooling over section features
    - Concept features: mean pooling over linked sentence embeddings
"""

import argparse
import json
import logging
import re
from pathlib import Path

import torch

from pathology_report_extraction.common.pdf_utils import ensure_dir, write_json
from pathology_report_extraction.common.pipeline_defaults import (
    CONCEPT_GRAPH_OUTPUT_SUBDIRS,
    CONCEPT_OUTPUT_SUBDIRS,
    CONCH_OUTPUT_SUBDIRS,
    DEFAULT_HIERARCHY_GRAPH_ROOT,
    DEFAULT_OUTPUT_ROOT,
    GRAPH_OUTPUT_SUBDIRS,
    HIERARCHY_GRAPH_TYPE_DIRS,
)
from pathology_report_extraction.config.config import get_bool, get_path, get_stage_config, get_value, load_yaml_config


LOGGER = logging.getLogger("build_text_hierarchy_graphs")

DEFAULT_INPUT_DIR = DEFAULT_OUTPUT_ROOT / CONCH_OUTPUT_SUBDIRS["masked"]
DEFAULT_OUTPUT_DIR = DEFAULT_HIERARCHY_GRAPH_ROOT
FEATURE_DIM = 512
DATASET_DIR_NAMES = {"BRCA", "KIRC", "LUSC"}

NODE_TYPE_TO_ID = {"document": 0, "section": 1, "sentence": 2}
EDGE_TYPE_TO_ID = {"parent": 0, "next": 1}
CONCEPT_NODE_TYPE_TO_ID = {"document": 0, "section": 1, "sentence": 2, "concept": 3}
CONCEPT_EDGE_TYPE_TO_ID = {
    "parent": 0,
    "next": 1,
    "mention": 2,
    "ontology": 3,
    "same_sentence": 4,
    "same_section": 5,
}
DEFAULT_EDGE_TYPE_WEIGHTS = {
    "parent": 1.0,
    "next": 0.25,
    "mention": 1.0,
    "ontology": 0.7,
    "same_sentence": 0.25,
    "same_section": 0.1,
}

CANONICAL_SECTION_TITLES = {
    "document body": "Document Body",
    "final diagnosis": "Final Diagnosis",
    "diagnosis": "Diagnosis",
    "gross description": "Gross Description",
    "microscopic description": "Microscopic Description",
    "clinical information": "Clinical Information",
    "comment": "Comment",
    "procedure": "Procedure",
    "synoptic report": "Synoptic Report",
    "summary of sections": "Summary of Sections",
    "specimen submitted": "Specimen Submitted",
    "ancillary studies": "Ancillary Studies",
    "intraoperative consultation": "Intraoperative Consultation",
    "patient history": "Patient History",
}


def iter_metadata_jsons(input_dir: Path) -> list[Path]:
    return sorted(
        path
        for path in input_dir.rglob("*.json")
        if path.is_file() and path.name not in {"run_summary.json"}
    )


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def resolve_library_relative_path(relative_path: Path, graph_type: str) -> Path:
    parts = relative_path.parts
    if parts and parts[0].upper() in DATASET_DIR_NAMES:
        return Path(parts[0]) / HIERARCHY_GRAPH_TYPE_DIRS[graph_type] / Path(*parts[1:])
    return Path(HIERARCHY_GRAPH_TYPE_DIRS[graph_type]) / relative_path


def load_optional_concept_annotation(
    metadata_json_path: Path,
    input_root: Path,
    concept_dir: Path | None,
) -> tuple[dict | None, str | None]:
    if concept_dir is None:
        return None, None

    annotation_root = Path(concept_dir)
    if not annotation_root.exists():
        return None, None

    relative_path = metadata_json_path.relative_to(input_root)
    concept_json_path = annotation_root / relative_path
    if not concept_json_path.exists():
        return None, str(concept_json_path)
    return load_json(concept_json_path), str(concept_json_path)


def normalize_section_title(raw_title: str) -> str:
    title = re.sub(r"\s+", " ", str(raw_title or "").strip())
    title = title.strip(" :;,-_/\\")
    if not title:
        return "Document Body"

    upper = title.upper()
    lower = title.lower()
    alpha_count = sum(ch.isalpha() for ch in title)
    digit_count = sum(ch.isdigit() for ch in title)
    weird_count = sum(not ch.isalnum() and not ch.isspace() for ch in title)

    if lower in CANONICAL_SECTION_TITLES:
        return CANONICAL_SECTION_TITLES[lower]
    if "FINAL" in upper and ("DIAGNOS" in upper or "DYAGNOS" in upper):
        return "Final Diagnosis"
    if "FINAL DIAGNOSIS" in upper or upper.startswith("PATH FINAL DIAGNOSIS"):
        return "Final Diagnosis"
    if "DIAGNOSIS" in upper or "NAL DIAGNOSIS" in upper:
        return "Diagnosis"
    if "GROSS DESCRIPTION" in upper:
        return "Gross Description"
    if "MICROSCOPIC DESCRIPTION" in upper:
        return "Microscopic Description"
    if "CLINICAL NOTE" in upper or "CLINICAL INFORMATION" in upper:
        return "Clinical Information"
    if upper.startswith("SPECIMEN"):
        return "Specimen Submitted"
    if "CHECKLIST" in upper or "SYNOPTIC" in upper or "CONSOLIDATED DIAGNOSTIC PATHOLOGY FORM" in upper:
        return "Synoptic Report"
    if "SUMMARY OF SECTIONS" in upper:
        return "Summary of Sections"
    if "INTRAOPERATIVE CONSULTATION" in upper:
        return "Intraoperative Consultation"
    if "ANCILLARY STUDIES" in upper:
        return "Ancillary Studies"
    if "HER2" in upper:
        return "Ancillary Studies"
    if "PATIENT HISTORY" in upper:
        return "Patient History"
    if "PROCEDURE" in upper:
        return "Procedure"
    if "COMMENT" in upper:
        return "Comment"
    if ("PATHO" in upper or "PATRFOLOGY" in upper or "PLOGY" in upper) and "REPORT" in upper:
        return "Document Body"
    if "TCGA-" in upper or re.search(r"\b\d{2,}[A-Z-]*\b", upper):
        return "Document Body"
    if upper.startswith("PAGE ") or upper.startswith("PACE "):
        return "Document Body"
    if "SURGICAL PATHOLOGY" in upper and "DIAGNOSIS" not in upper:
        return "Document Body"
    if upper in {"MRN", "MR #", "NAME", "KARYOTYPE", "I", "J", "E", "B", "SPECIMEN"}:
        return "Document Body"
    if re.fullmatch(r"[A-Z]", upper):
        return "Document Body"
    if re.fullmatch(r"[A-Z0-9#/\\-]{1,8}", upper):
        return "Document Body"
    if alpha_count <= 4 and (digit_count > 0 or weird_count > 0):
        return "Document Body"
    if weird_count >= 2 and digit_count >= 1:
        return "Document Body"
    return title


def infer_source_paths(payload: dict, metadata_json_path: Path, input_root: Path) -> tuple[str | None, str | None]:
    relative_path = metadata_json_path.relative_to(input_root)
    output_root = input_root.parent
    sentence_view_path = output_root / "sentence_exports_masked" / relative_path

    source_sentence_view_json = str(sentence_view_path) if sentence_view_path.exists() else payload.get("source_sentence_view_json")
    source_preprocessed_json = payload.get("source_preprocessed_json") or payload.get("source_sentence_json")

    if sentence_view_path.exists():
        try:
            sentence_view_payload = load_json(sentence_view_path)
            source_preprocessed_json = sentence_view_payload.get("source_json") or source_preprocessed_json
        except Exception:
            pass

    if source_preprocessed_json:
        preprocessed_path = Path(source_preprocessed_json)
        if not preprocessed_path.exists():
            parts = list(preprocessed_path.parts)
            for folder_name in (
                "pathology_report_preprocessed_masked",
                "pathology_report_preprocessed_no_diagnosis",
                "pathology_report_preprocessed_no_diagnosis_masked",
                "pathology_report_preprocessed_full",
            ):
                if folder_name in parts:
                    idx = parts.index(folder_name)
                    candidate = output_root.joinpath(*parts[idx:])
                    if candidate.exists():
                        source_preprocessed_json = str(candidate)
                        break

    return source_sentence_view_json, source_preprocessed_json


def clean_payload(payload: dict, metadata_json_path: Path, input_root: Path) -> dict:
    cleaned = dict(payload)
    source_sentence_view_json, source_preprocessed_json = infer_source_paths(
        payload=payload,
        metadata_json_path=metadata_json_path,
        input_root=input_root,
    )
    cleaned["source_sentence_view_json"] = source_sentence_view_json
    cleaned["source_preprocessed_json"] = source_preprocessed_json

    raw_sections = sorted(payload.get("sections", []), key=lambda item: int(item.get("section_index", 0)))
    raw_sentence_records = sorted(payload.get("sentence_records", []), key=lambda item: int(item.get("sentence_index", 0)))
    sentence_record_map = {
        int(record.get("sentence_index", index)): record
        for index, record in enumerate(raw_sentence_records)
    }

    merged_sections: list[dict] = []
    cleaned_sentence_records: list[dict] = []
    sentence_to_section: list[int] = []
    renamed_section_count = 0
    merged_section_count = 0

    for raw_section in raw_sections:
        start = int(raw_section.get("sentence_start", 0))
        end = int(raw_section.get("sentence_end", start))
        if end <= start:
            continue

        original_title = str(raw_section.get("section_title", "Document Body"))
        normalized_title = normalize_section_title(original_title)
        if normalized_title != original_title:
            renamed_section_count += 1

        if (
            merged_sections
            and merged_sections[-1]["section_title"] == normalized_title
            and int(merged_sections[-1]["sentence_end"]) == start
        ):
            section_index = int(merged_sections[-1]["section_index"])
            merged_sections[-1]["sentence_end"] = end
            merged_sections[-1]["sentence_count"] = end - int(merged_sections[-1]["sentence_start"])
            merged_section_count += 1
        else:
            section_index = len(merged_sections)
            merged_sections.append(
                {
                    "section_index": section_index,
                    "section_title": normalized_title,
                    "sentence_start": start,
                    "sentence_end": end,
                    "sentence_count": end - start,
                }
            )

        section_start = int(merged_sections[section_index]["sentence_start"])
        for sentence_index in range(start, end):
            record = dict(sentence_record_map.get(sentence_index, {}))
            record["sentence_index"] = sentence_index
            record["section_index"] = section_index
            record["section_title"] = normalized_title
            record["section_sentence_index"] = sentence_index - section_start
            cleaned_sentence_records.append(record)
            sentence_to_section.append(section_index)

    cleaned["sections"] = merged_sections
    cleaned["sentence_records"] = cleaned_sentence_records
    cleaned["sentence_to_section"] = sentence_to_section
    cleaned["section_count"] = len(merged_sections)
    cleaned["sentence_count"] = len(cleaned_sentence_records)
    cleaned["graph_cleanup"] = {
        "original_section_count": len(raw_sections),
        "cleaned_section_count": len(merged_sections),
        "renamed_section_count": renamed_section_count,
        "merged_section_count": merged_section_count,
    }
    return cleaned


def mean_pool(features: torch.Tensor) -> torch.Tensor:
    if features.numel() == 0:
        return torch.zeros(FEATURE_DIM, dtype=torch.float32)
    return features.mean(dim=0)


def validate_payload(payload: dict, sentence_features: torch.Tensor) -> None:
    sentence_count = int(payload.get("sentence_count", 0))
    if sentence_features.ndim != 2:
        raise ValueError(f"Expected sentence feature tensor to be 2D, got shape {tuple(sentence_features.shape)}")
    if sentence_features.shape[1] != FEATURE_DIM:
        raise ValueError(f"Expected feature dim {FEATURE_DIM}, got {sentence_features.shape[1]}")
    if sentence_features.shape[0] != sentence_count:
        raise ValueError(
            f"Sentence count mismatch: metadata has {sentence_count}, tensor has {sentence_features.shape[0]}"
        )


def build_section_features(payload: dict, sentence_features: torch.Tensor) -> torch.Tensor:
    pooled: list[torch.Tensor] = []
    for section in payload.get("sections", []):
        start = int(section["sentence_start"])
        end = int(section["sentence_end"])
        pooled.append(mean_pool(sentence_features[start:end]))
    if not pooled:
        return torch.empty((0, FEATURE_DIM), dtype=torch.float32)
    return torch.stack(pooled, dim=0).float()


def build_document_feature(section_features: torch.Tensor, sentence_features: torch.Tensor) -> torch.Tensor:
    if section_features.numel() > 0:
        return mean_pool(section_features).float()
    return mean_pool(sentence_features).float()

def build_concept_features(
    concept_annotation: dict | None,
    sentence_features: torch.Tensor,
) -> tuple[torch.Tensor, list[str], torch.Tensor, torch.Tensor, torch.Tensor, list[list[int]]]:
    if not concept_annotation:
        return (
            torch.empty((0, FEATURE_DIM), dtype=torch.float32),
            [],
            torch.empty((0,), dtype=torch.float32),
            torch.empty((0,), dtype=torch.float32),
            torch.empty((0,), dtype=torch.float32),
            [],
        )

    concept_features: list[torch.Tensor] = []
    concept_ids: list[str] = []
    concept_ic: list[float] = []
    concept_depth: list[float] = []
    concept_direct_mentions: list[float] = []
    concept_sentence_links: list[list[int]] = []

    for concept in concept_annotation.get("concepts", []) or []:
        sentence_indices = sorted(
            {
                int(index)
                for index in concept.get("sentence_indices", []) or []
                if 0 <= int(index) < int(sentence_features.shape[0])
            }
        )
        if sentence_indices:
            concept_feature = mean_pool(sentence_features[sentence_indices])
        else:
            concept_feature = mean_pool(sentence_features)

        concept_features.append(concept_feature.float())
        concept_ids.append(str(concept.get("concept_id", "")))
        concept_ic.append(float(concept.get("ic", 0.0)))
        concept_depth.append(float(concept.get("depth", 0.0)))
        concept_direct_mentions.append(float(concept.get("direct_mention_count", 0.0)))
        concept_sentence_links.append(sentence_indices)

    if not concept_features:
        return (
            torch.empty((0, FEATURE_DIM), dtype=torch.float32),
            [],
            torch.empty((0,), dtype=torch.float32),
            torch.empty((0,), dtype=torch.float32),
            torch.empty((0,), dtype=torch.float32),
            [],
        )

    return (
        torch.stack(concept_features, dim=0).float(),
        concept_ids,
        torch.tensor(concept_ic, dtype=torch.float32),
        torch.tensor(concept_depth, dtype=torch.float32),
        torch.tensor(concept_direct_mentions, dtype=torch.float32),
        concept_sentence_links,
    )


def build_nodes(payload: dict, concept_annotation: dict | None = None) -> tuple[list[dict], list[int], list[int], dict[str, int]]:
    nodes: list[dict] = []
    section_node_indices: list[int] = []
    sentence_node_indices: list[int] = []
    concept_node_indices: dict[str, int] = {}

    nodes.append(
        {
            "node_index": 0,
            "node_id": "doc_0",
            "node_type": "document",
            "title": payload.get("document_id") or payload.get("file_name") or "document",
            "level": 0,
        }
    )

    for section in payload.get("sections", []):
        node_index = len(nodes)
        section_index = int(section["section_index"])
        section_node_indices.append(node_index)
        nodes.append(
            {
                "node_index": node_index,
                "node_id": f"sec_{section_index}",
                "node_type": "section",
                "level": 1,
                "section_index": section_index,
                "section_title": section["section_title"],
                "sentence_start": int(section["sentence_start"]),
                "sentence_end": int(section["sentence_end"]),
                "sentence_count": int(section["sentence_count"]),
            }
        )

    for record in payload.get("sentence_records", []):
        node_index = len(nodes)
        sentence_index = int(record["sentence_index"])
        sentence_node_indices.append(node_index)
        nodes.append(
            {
                "node_index": node_index,
                "node_id": f"sent_{sentence_index}",
                "node_type": "sentence",
                "level": 2,
                "sentence_index": sentence_index,
                "section_index": int(record["section_index"]),
                "section_title": record["section_title"],
                "section_sentence_index": int(record["section_sentence_index"]),
                "text": record["text"],
            }
        )

    for concept in concept_annotation.get("concepts", []) if concept_annotation else []:
        node_index = len(nodes)
        concept_id = str(concept.get("concept_id", ""))
        concept_node_indices[concept_id] = node_index
        nodes.append(
            {
                "node_index": node_index,
                "node_id": f"concept_{concept_id}",
                "node_type": "concept",
                "level": 3,
                "concept_id": concept_id,
                "concept_name": str(concept.get("concept_name", concept_id)),
                "depth": int(concept.get("depth", 0)),
                "ic": float(concept.get("ic", 0.0)),
                "direct_mention_count": int(concept.get("direct_mention_count", 0)),
                "is_direct": bool(concept.get("is_direct", False)),
                "is_ancestor_only": bool(concept.get("is_ancestor_only", False)),
                "sentence_indices": list(concept.get("sentence_indices", []) or []),
            }
        )

    return nodes, section_node_indices, sentence_node_indices, concept_node_indices


def build_edges(
    payload: dict,
    section_node_indices: list[int],
    sentence_node_indices: list[int],
    concept_node_indices: dict[str, int] | None = None,
    concept_annotation: dict | None = None,
    add_concept_cooccurrence_edges: bool = True,
) -> list[dict]:
    edges: list[dict] = []
    concept_node_indices = concept_node_indices or {}

    # Parent edges: document -> section
    for section_index, section_node_index in enumerate(section_node_indices):
        edges.append(
            {
                "source_index": 0,
                "target_index": section_node_index,
                "edge_type": "parent",
                "source_type": "document",
                "target_type": "section",
                "section_index": section_index,
            }
        )

    # Parent edges: section -> sentence
    sentence_to_section = payload.get("sentence_to_section", [])
    for sentence_index, section_index in enumerate(sentence_to_section):
        section_index = int(section_index)
        sentence_node_index = sentence_node_indices[sentence_index]
        edges.append(
            {
                "source_index": section_node_indices[section_index],
                "target_index": sentence_node_index,
                "edge_type": "parent",
                "source_type": "section",
                "target_type": "sentence",
                "section_index": section_index,
                "sentence_index": sentence_index,
            }
        )

    # Next edges: section order
    for i in range(len(section_node_indices) - 1):
        edges.append(
            {
                "source_index": section_node_indices[i],
                "target_index": section_node_indices[i + 1],
                "edge_type": "next",
                "source_type": "section",
                "target_type": "section",
            }
        )

    # Next edges: sentence order across full document
    for i in range(len(sentence_node_indices) - 1):
        edges.append(
            {
                "source_index": sentence_node_indices[i],
                "target_index": sentence_node_indices[i + 1],
                "edge_type": "next",
                "source_type": "sentence",
                "target_type": "sentence",
            }
        )

    if concept_annotation and concept_node_indices:
        mention_edge_keys: set[tuple[int, int, str]] = set()
        sentence_to_concepts: dict[int, set[str]] = {}
        section_to_concepts: dict[int, set[str]] = {}

        for mention in concept_annotation.get("mentions", []) or []:
            concept_id = str(mention.get("concept_id", ""))
            sentence_index = int(mention.get("sentence_index", -1))
            section_index = int(mention.get("section_index", -1))
            if concept_id not in concept_node_indices:
                continue
            if not (0 <= sentence_index < len(sentence_node_indices)):
                continue

            source_index = sentence_node_indices[sentence_index]
            target_index = concept_node_indices[concept_id]
            edge_key = (source_index, target_index, "mention")
            if edge_key not in mention_edge_keys:
                mention_edge_keys.add(edge_key)
                edges.append(
                    {
                        "source_index": source_index,
                        "target_index": target_index,
                        "edge_type": "mention",
                        "source_type": "sentence",
                        "target_type": "concept",
                        "sentence_index": sentence_index,
                        "section_index": section_index,
                        "concept_id": concept_id,
                    }
                )

            sentence_to_concepts.setdefault(sentence_index, set()).add(concept_id)
            if section_index >= 0:
                section_to_concepts.setdefault(section_index, set()).add(concept_id)

        ontology_edge_keys: set[tuple[int, int, str]] = set()
        for concept_edge in concept_annotation.get("concept_edges", []) or []:
            source_concept_id = str(concept_edge.get("source_concept_id", ""))
            target_concept_id = str(concept_edge.get("target_concept_id", ""))
            if source_concept_id not in concept_node_indices or target_concept_id not in concept_node_indices:
                continue
            edge_key = (
                concept_node_indices[source_concept_id],
                concept_node_indices[target_concept_id],
                "ontology",
            )
            if edge_key in ontology_edge_keys:
                continue
            ontology_edge_keys.add(edge_key)
            edges.append(
                {
                    "source_index": concept_node_indices[source_concept_id],
                    "target_index": concept_node_indices[target_concept_id],
                    "edge_type": "ontology",
                    "source_type": "concept",
                    "target_type": "concept",
                    "source_concept_id": source_concept_id,
                    "target_concept_id": target_concept_id,
                }
            )

        if add_concept_cooccurrence_edges:
            cooccurrence_edge_keys: set[tuple[int, int, str]] = set()
            for sentence_index, concept_ids in sentence_to_concepts.items():
                sorted_ids = sorted(concept_ids)
                for i in range(len(sorted_ids)):
                    for j in range(i + 1, len(sorted_ids)):
                        left_id = sorted_ids[i]
                        right_id = sorted_ids[j]
                        edge_key = (
                            concept_node_indices[left_id],
                            concept_node_indices[right_id],
                            "same_sentence",
                        )
                        if edge_key in cooccurrence_edge_keys:
                            continue
                        cooccurrence_edge_keys.add(edge_key)
                        edges.append(
                            {
                                "source_index": concept_node_indices[left_id],
                                "target_index": concept_node_indices[right_id],
                                "edge_type": "same_sentence",
                                "source_type": "concept",
                                "target_type": "concept",
                                "sentence_index": sentence_index,
                            }
                        )

            for section_index, concept_ids in section_to_concepts.items():
                sorted_ids = sorted(concept_ids)
                for i in range(len(sorted_ids)):
                    for j in range(i + 1, len(sorted_ids)):
                        left_id = sorted_ids[i]
                        right_id = sorted_ids[j]
                        edge_key = (
                            concept_node_indices[left_id],
                            concept_node_indices[right_id],
                            "same_section",
                        )
                        if edge_key in cooccurrence_edge_keys:
                            continue
                        cooccurrence_edge_keys.add(edge_key)
                        edges.append(
                            {
                                "source_index": concept_node_indices[left_id],
                                "target_index": concept_node_indices[right_id],
                                "edge_type": "same_section",
                                "source_type": "concept",
                                "target_type": "concept",
                                "section_index": section_index,
                            }
                        )

    return edges


def build_edge_tensors(edges: list[dict], edge_type_mapping: dict[str, int]) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    if not edges:
        return (
            torch.empty((2, 0), dtype=torch.long),
            torch.empty((0,), dtype=torch.long),
            torch.empty((0,), dtype=torch.float32),
        )
    edge_index = torch.tensor(
        [[int(edge["source_index"]) for edge in edges], [int(edge["target_index"]) for edge in edges]],
        dtype=torch.long,
    )
    edge_type = torch.tensor([edge_type_mapping[edge["edge_type"]] for edge in edges], dtype=torch.long)
    edge_weight = torch.tensor(
        [float(edge.get("edge_weight", DEFAULT_EDGE_TYPE_WEIGHTS.get(str(edge["edge_type"]), 1.0))) for edge in edges],
        dtype=torch.float32,
    )
    return edge_index, edge_type, edge_weight


def build_node_feature_matrix(
    document_feature: torch.Tensor,
    section_features: torch.Tensor,
    sentence_features: torch.Tensor,
    concept_features: torch.Tensor | None = None,
) -> torch.Tensor:
    pieces = [document_feature.view(1, -1).float()]
    if section_features.numel() > 0:
        pieces.append(section_features.float())
    if sentence_features.numel() > 0:
        pieces.append(sentence_features.float())
    if concept_features is not None and concept_features.numel() > 0:
        pieces.append(concept_features.float())
    return torch.cat(pieces, dim=0)


def build_node_type_tensor(
    section_count: int,
    sentence_count: int,
    concept_count: int,
    node_type_mapping: dict[str, int],
) -> torch.Tensor:
    node_types = [node_type_mapping["document"]]
    node_types.extend([node_type_mapping["section"]] * section_count)
    node_types.extend([node_type_mapping["sentence"]] * sentence_count)
    if "concept" in node_type_mapping:
        node_types.extend([node_type_mapping["concept"]] * concept_count)
    return torch.tensor(node_types, dtype=torch.long)


def build_graph_payload(
    payload: dict,
    sentence_features: torch.Tensor,
    concept_annotation: dict | None = None,
    attach_concepts: bool = False,
    add_concept_cooccurrence_edges: bool = True,
) -> tuple[dict, dict]:
    validate_payload(payload, sentence_features)

    section_features = build_section_features(payload, sentence_features)
    document_feature = build_document_feature(section_features, sentence_features)
    concept_features, concept_ids, concept_ic, concept_depth, concept_direct_mentions, concept_sentence_links = build_concept_features(
        concept_annotation=concept_annotation,
        sentence_features=sentence_features,
    )

    node_type_mapping = CONCEPT_NODE_TYPE_TO_ID if attach_concepts else NODE_TYPE_TO_ID
    edge_type_mapping = CONCEPT_EDGE_TYPE_TO_ID if attach_concepts else EDGE_TYPE_TO_ID

    nodes, section_node_indices, sentence_node_indices, concept_node_indices = build_nodes(
        payload,
        concept_annotation=concept_annotation if attach_concepts else None,
    )
    edges = build_edges(
        payload,
        section_node_indices=section_node_indices,
        sentence_node_indices=sentence_node_indices,
        concept_node_indices=concept_node_indices,
        concept_annotation=concept_annotation if attach_concepts else None,
        add_concept_cooccurrence_edges=add_concept_cooccurrence_edges,
    )
    for edge in edges:
        edge.setdefault("edge_weight", DEFAULT_EDGE_TYPE_WEIGHTS.get(str(edge.get("edge_type", "")), 1.0))
    edge_index, edge_type, edge_weight = build_edge_tensors(edges, edge_type_mapping=edge_type_mapping)

    node_features = build_node_feature_matrix(
        document_feature=document_feature,
        section_features=section_features,
        sentence_features=sentence_features,
        concept_features=concept_features if attach_concepts else None,
    )
    node_type = build_node_type_tensor(
        section_count=section_features.shape[0],
        sentence_count=sentence_features.shape[0],
        concept_count=concept_features.shape[0] if attach_concepts else 0,
        node_type_mapping=node_type_mapping,
    )

    graph_tensor_payload = {
        "document_feature": document_feature.float(),
        "section_features": section_features.float(),
        "sentence_features": sentence_features.float(),
        "concept_features": concept_features.float(),
        "concept_ids": concept_ids,
        "concept_ic": concept_ic,
        "concept_depth": concept_depth,
        "concept_direct_mentions": concept_direct_mentions,
        "concept_sentence_links": concept_sentence_links,
        "node_features": node_features.float(),
        "node_type": node_type,
        "edge_index": edge_index,
        "edge_type": edge_type,
        "edge_weight": edge_weight,
        "sentence_to_section": torch.tensor(payload.get("sentence_to_section", []), dtype=torch.long),
        "section_spans": torch.tensor(
            [[int(section["sentence_start"]), int(section["sentence_end"])] for section in payload.get("sections", [])],
            dtype=torch.long,
        )
        if payload.get("sections")
        else torch.empty((0, 2), dtype=torch.long),
        "node_type_mapping": node_type_mapping,
        "edge_type_mapping": edge_type_mapping,
    }

    graph_json_payload = {
        "document_id": payload.get("document_id"),
        "file_name": payload.get("file_name"),
        "dataset": payload.get("dataset"),
        "filter_mode": payload.get("filter_mode"),
        "source_pdf": payload.get("source_pdf"),
        "source_sentence_view_json": payload.get("source_sentence_view_json"),
        "source_preprocessed_json": payload.get("source_preprocessed_json") or payload.get("source_sentence_json"),
        "source_concept_json": None,
        "embedding_path": payload.get("embedding_path"),
        "pooling": "mean",
        "feature_dim": FEATURE_DIM,
        "graph_variant": "concept_graph" if attach_concepts else "hierarchy_graph",
        "graph_cleanup": payload.get("graph_cleanup", {}),
        "node_type_mapping": node_type_mapping,
        "edge_type_mapping": edge_type_mapping,
        "node_count": len(nodes),
        "edge_count": len(edges),
        "node_counts": {
            "document": 1,
            "section": int(section_features.shape[0]),
            "sentence": int(sentence_features.shape[0]),
            "concept": int(concept_features.shape[0]),
        },
        "concept_count": int(concept_features.shape[0]),
        "concept_annotation_summary": {
            "mention_count": int(concept_annotation.get("mention_count", 0)) if concept_annotation else 0,
            "direct_concept_count": int(concept_annotation.get("direct_concept_count", 0)) if concept_annotation else 0,
        },
        "nodes": nodes,
        "edges": edges,
    }
    return graph_tensor_payload, graph_json_payload


def build_graph_for_document(
    metadata_json_path: Path,
    input_root: Path,
    output_root: Path,
    concept_dir: Path | None = None,
    attach_concepts: bool = False,
    add_concept_cooccurrence_edges: bool = True,
) -> dict:
    payload = clean_payload(load_json(metadata_json_path), metadata_json_path=metadata_json_path, input_root=input_root)
    relative_path = metadata_json_path.relative_to(input_root)
    if Path(output_root).resolve() == DEFAULT_HIERARCHY_GRAPH_ROOT.resolve() and not attach_concepts:
        relative_path = resolve_library_relative_path(relative_path, "basic")
    output_json_path = output_root / relative_path
    output_pt_path = output_root / relative_path.with_suffix(".pt")
    ensure_dir(output_json_path.parent)

    embedding_path = metadata_json_path.with_suffix(".pt")
    if not embedding_path.exists():
        embedding_path = Path(payload["embedding_path"])
    payload["embedding_path"] = str(embedding_path)
    sentence_features = torch.load(embedding_path, map_location="cpu")
    concept_annotation, concept_json_path = load_optional_concept_annotation(
        metadata_json_path=metadata_json_path,
        input_root=input_root,
        concept_dir=concept_dir if attach_concepts else None,
    )

    if int(payload.get("sentence_count", 0)) == 0:
        if output_json_path.exists():
            output_json_path.unlink()
        if output_pt_path.exists():
            output_pt_path.unlink()
        return {
            "document_id": payload.get("document_id"),
            "file_name": payload.get("file_name"),
            "dataset": payload.get("dataset"),
            "source_embedding_json": str(metadata_json_path),
            "source_embedding_pt": str(embedding_path),
            "output_graph_json": None,
            "output_graph_pt": None,
            "node_count": 0,
            "edge_count": 0,
            "sentence_count": 0,
            "section_count": 0,
            "concept_count": 0,
            "status": "skipped",
            "skip_reason": "empty_graph_after_cleanup",
            "graph_cleanup": payload.get("graph_cleanup", {}),
        }

    graph_tensor_payload, graph_json_payload = build_graph_payload(
        payload,
        sentence_features=sentence_features,
        concept_annotation=concept_annotation,
        attach_concepts=attach_concepts,
        add_concept_cooccurrence_edges=add_concept_cooccurrence_edges,
    )
    graph_json_payload["source_concept_json"] = concept_json_path

    torch.save(graph_tensor_payload, output_pt_path)
    graph_json_payload["graph_tensor_path"] = str(output_pt_path)
    write_json(output_json_path, graph_json_payload)

    return {
        "document_id": payload.get("document_id"),
        "file_name": payload.get("file_name"),
        "dataset": payload.get("dataset"),
        "source_embedding_json": str(metadata_json_path),
        "source_embedding_pt": str(embedding_path),
        "output_graph_json": str(output_json_path),
        "output_graph_pt": str(output_pt_path),
        "node_count": graph_json_payload["node_count"],
        "edge_count": graph_json_payload["edge_count"],
        "sentence_count": graph_json_payload["node_counts"]["sentence"],
        "section_count": graph_json_payload["node_counts"]["section"],
        "concept_count": graph_json_payload["node_counts"].get("concept", 0),
        "status": "success",
        "graph_cleanup": payload.get("graph_cleanup", {}),
    }


def process_all_documents(
    input_dir: Path,
    output_dir: Path,
    concept_dir: Path | None = None,
    attach_concepts: bool = False,
    add_concept_cooccurrence_edges: bool = True,
    limit: int | None = None,
) -> dict:
    input_root = Path(input_dir)
    output_root = Path(output_dir)
    ensure_dir(output_root)

    log_path = output_root / "graph.log"
    root_logger = logging.getLogger()
    for handler in list(root_logger.handlers):
        root_logger.removeHandler(handler)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        handlers=[
            logging.FileHandler(log_path, encoding="utf-8"),
            logging.StreamHandler(),
        ],
    )

    metadata_paths = iter_metadata_jsons(input_root)
    if limit is not None:
        metadata_paths = metadata_paths[:limit]

    concept_root = Path(concept_dir) if concept_dir is not None else None
    if attach_concepts and concept_root is not None and not concept_root.exists():
        LOGGER.warning("Concept annotation directory does not exist yet: %s", concept_root)

    LOGGER.info("Discovered %s embedding metadata JSON files under %s", len(metadata_paths), input_root)

    summaries: list[dict] = []
    for index, metadata_json_path in enumerate(metadata_paths, start=1):
        LOGGER.info("[%s/%s] Building graph for %s", index, len(metadata_paths), metadata_json_path)
        try:
            summary = build_graph_for_document(
                metadata_json_path=metadata_json_path,
                input_root=input_root,
                output_root=output_root,
                concept_dir=concept_root,
                attach_concepts=attach_concepts,
                add_concept_cooccurrence_edges=add_concept_cooccurrence_edges,
            )
        except Exception as exc:
            LOGGER.exception("Failed to build graph for %s", metadata_json_path)
            summary = {
                "document_id": metadata_json_path.stem,
                "file_name": metadata_json_path.name,
                "dataset": None,
                "source_embedding_json": str(metadata_json_path),
                "source_embedding_pt": None,
                "output_graph_json": None,
                "output_graph_pt": None,
                "node_count": 0,
                "edge_count": 0,
                "sentence_count": 0,
                "section_count": 0,
                "concept_count": 0,
                "status": "failed",
                "error": str(exc),
            }
        summaries.append(summary)

    successes = [item for item in summaries if item["status"] == "success"]
    failures = [item for item in summaries if item["status"] == "failed"]
    skipped = [item for item in summaries if item["status"] == "skipped"]

    dataset_counts: dict[str, int] = {}
    for item in successes:
        dataset = item.get("dataset") or "UNKNOWN"
        dataset_counts[dataset] = dataset_counts.get(dataset, 0) + 1

    run_summary = {
        "input_dir": str(input_root),
        "output_dir": str(output_root),
        "concept_dir": str(concept_root) if concept_root is not None else None,
        "pooling": "mean",
        "feature_dim": FEATURE_DIM,
        "graph_schema": {
            "node_levels": ["document", "section", "sentence", "concept"] if attach_concepts else ["document", "section", "sentence"],
            "edge_types": list(CONCEPT_EDGE_TYPE_TO_ID) if attach_concepts else ["parent", "next"],
            "edge_type_weights": {
                key: DEFAULT_EDGE_TYPE_WEIGHTS[key]
                for key in (CONCEPT_EDGE_TYPE_TO_ID if attach_concepts else EDGE_TYPE_TO_ID)
                if key in DEFAULT_EDGE_TYPE_WEIGHTS
            },
        },
        "attach_concepts": bool(attach_concepts),
        "add_concept_cooccurrence_edges": bool(add_concept_cooccurrence_edges),
        "total_metadata_files": len(metadata_paths),
        "success_count": len(successes),
        "skipped_count": len(skipped),
        "failure_count": len(failures),
        "datasets": dataset_counts,
        "files": summaries,
    }
    write_json(output_root / "run_summary.json", run_summary)
    LOGGER.info(
        "Completed graph build | total=%s | success=%s | skipped=%s | failed=%s",
        len(metadata_paths),
        len(successes),
        len(skipped),
        len(failures),
    )
    return run_summary


def parse_args() -> argparse.Namespace:
    pre_parser = argparse.ArgumentParser(add_help=False)
    pre_parser.add_argument("--config", type=Path, default=None, help="Optional YAML config preset.")
    pre_args, _ = pre_parser.parse_known_args()
    raw_config, config_path = load_yaml_config(pre_args.config)
    stage_block = raw_config.get("build_text_hierarchy_graphs") if isinstance(raw_config.get("build_text_hierarchy_graphs"), dict) else {}
    config = get_stage_config(raw_config, "build_text_hierarchy_graphs")
    defaults_block = raw_config.get("defaults") if isinstance(raw_config.get("defaults"), dict) else {}
    preprocess_config = get_stage_config(raw_config, "preprocess")
    filter_mode = str(get_value(preprocess_config, "filter_mode", "masked"))
    output_root = get_path(defaults_block, "output_root", DEFAULT_OUTPUT_ROOT, config_path)

    concept_default = None
    attach_concepts_default = get_bool(config, "attach_concepts", False)
    output_dir_default = DEFAULT_OUTPUT_DIR
    if attach_concepts_default:
        output_dir_default = DEFAULT_OUTPUT_ROOT / CONCEPT_GRAPH_OUTPUT_SUBDIRS["masked"]

    input_default = get_path(stage_block, "input_dir", DEFAULT_INPUT_DIR, config_path)
    output_default = get_path(stage_block, "output_dir", output_dir_default, config_path)

    if stage_block:
        if stage_block.get("input_dir") in (None, ""):
            conch_output_subdirs = dict(CONCH_OUTPUT_SUBDIRS)
            conch_output_subdirs.update(get_value(get_stage_config(raw_config, "encode_sentence_exports_conch"), "output_subdirs", {}) or {})
            input_default = output_root / conch_output_subdirs.get(filter_mode, CONCH_OUTPUT_SUBDIRS["masked"])
        if stage_block.get("output_dir") in (None, ""):
            graph_output_subdirs = dict(
                CONCEPT_GRAPH_OUTPUT_SUBDIRS if attach_concepts_default else GRAPH_OUTPUT_SUBDIRS
            )
            graph_output_subdirs.update(get_value(config, "output_subdirs", {}) or {})
            default_key = "masked"
            output_default = (
                output_root / graph_output_subdirs.get(filter_mode, graph_output_subdirs[default_key])
                if attach_concepts_default
                else DEFAULT_HIERARCHY_GRAPH_ROOT
            )
        if attach_concepts_default:
            concept_output_subdirs = dict(CONCEPT_OUTPUT_SUBDIRS)
            concept_output_subdirs.update(
                get_value(get_stage_config(raw_config, "extract_ontology_concepts"), "output_subdirs", {}) or {}
            )
            concept_default = get_path(
                stage_block,
                "concept_dir",
                output_root / concept_output_subdirs.get(filter_mode, CONCEPT_OUTPUT_SUBDIRS["masked"]),
                config_path,
            )

    parser = argparse.ArgumentParser(
        description="Build Document -> Section -> Sentence hierarchy graphs with optional concept nodes from sentence-level CONCH embeddings."
    )
    parser.add_argument("--config", type=Path, default=pre_args.config, help="Optional YAML config preset.")
    parser.add_argument(
        "--input_dir",
        type=Path,
        default=input_default,
        help="Directory containing embedding metadata JSON files.",
    )
    parser.add_argument(
        "--output_dir",
        type=Path,
        default=output_default,
        help="Directory for hierarchy graph outputs.",
    )
    parser.add_argument(
        "--concept_dir",
        type=Path,
        default=concept_default,
        help="Optional directory containing concept annotation JSON files aligned with the embedding metadata layout.",
    )
    parser.add_argument(
        "--attach_concepts",
        action="store_true",
        default=attach_concepts_default,
        help="Attach concept nodes and ontology-aware edges when concept annotations are available.",
    )
    parser.add_argument(
        "--disable_concept_cooccurrence_edges",
        action="store_true",
        default=not get_bool(config, "add_concept_cooccurrence_edges", True),
        help="Skip same-sentence and same-section concept co-occurrence edges.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None if get_value(config, "limit", None) is None else int(get_value(config, "limit", None)),
        help="Optional cap on number of documents to convert.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    summary = process_all_documents(
        input_dir=args.input_dir,
        output_dir=args.output_dir,
        concept_dir=args.concept_dir,
        attach_concepts=args.attach_concepts,
        add_concept_cooccurrence_edges=not args.disable_concept_cooccurrence_edges,
        limit=args.limit,
    )
    print(
        f"Built graphs for {summary['total_metadata_files']} files | success={summary['success_count']} | "
        f"failed={summary['failure_count']}"
    )


if __name__ == "__main__":
    main()
