from __future__ import annotations

"""Build simple Document -> Section -> Sentence hierarchy graphs.

Dependencies:
    pip install torch

Input:
    sentence-level CONCH embeddings plus metadata generated by
    encode_sentence_exports_conch.py

Output:
    One .pt file per document with graph tensors and one companion .json file
    with human-readable node/edge metadata.

Graph design in this first version:
    - Node levels: Document, Section, Sentence
    - Edge types: parent, next
    - Sentence features: original CONCH embeddings
    - Section features: mean pooling over child sentences
    - Document feature: mean pooling over section features
"""

import argparse
import json
import logging
import re
from pathlib import Path

import torch

from config.config import get_path, get_stage_config, get_value, load_yaml_config
from pdf_utils import ensure_dir, write_json


LOGGER = logging.getLogger("build_text_hierarchy_graphs")

DEFAULT_OUTPUT_ROOT = Path(r"D:\Tasks\isbi_code\pathology_report_extraction\Output")
DEFAULT_INPUT_DIR = DEFAULT_OUTPUT_ROOT / "sentence_embeddings_conch_masked"
DEFAULT_OUTPUT_DIR = DEFAULT_OUTPUT_ROOT / "text_hierarchy_graphs_masked"
DEFAULT_CONCH_OUTPUT_SUBDIRS = {
    "masked": "sentence_embeddings_conch_masked",
    "no_diagnosis": "sentence_embeddings_conch_no_diagnosis",
    "no_diagnosis_masked": "sentence_embeddings_conch_no_diagnosis_masked",
    "full": "sentence_embeddings_conch_full",
}
DEFAULT_GRAPH_OUTPUT_SUBDIRS = {
    "masked": "text_hierarchy_graphs_masked",
    "no_diagnosis": "text_hierarchy_graphs_no_diagnosis",
    "no_diagnosis_masked": "text_hierarchy_graphs_no_diagnosis_masked",
    "full": "text_hierarchy_graphs_full",
}
FEATURE_DIM = 512

NODE_TYPE_TO_ID = {"document": 0, "section": 1, "sentence": 2}
EDGE_TYPE_TO_ID = {"parent": 0, "next": 1}

CANONICAL_SECTION_TITLES = {
    "document body": "Document Body",
    "final diagnosis": "Final Diagnosis",
    "diagnosis": "Diagnosis",
    "gross description": "Gross Description",
    "microscopic description": "Microscopic Description",
    "clinical information": "Clinical Information",
    "comment": "Comment",
    "procedure": "Procedure",
    "synoptic report": "Synoptic Report",
    "summary of sections": "Summary of Sections",
    "specimen submitted": "Specimen Submitted",
    "ancillary studies": "Ancillary Studies",
    "intraoperative consultation": "Intraoperative Consultation",
    "patient history": "Patient History",
}


def iter_metadata_jsons(input_dir: Path) -> list[Path]:
    return sorted(
        path
        for path in input_dir.rglob("*.json")
        if path.is_file() and path.name not in {"run_summary.json"}
    )


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def normalize_section_title(raw_title: str) -> str:
    title = re.sub(r"\s+", " ", str(raw_title or "").strip())
    title = title.strip(" :;,-_/\\")
    if not title:
        return "Document Body"

    upper = title.upper()
    lower = title.lower()
    alpha_count = sum(ch.isalpha() for ch in title)
    digit_count = sum(ch.isdigit() for ch in title)
    weird_count = sum(not ch.isalnum() and not ch.isspace() for ch in title)

    if lower in CANONICAL_SECTION_TITLES:
        return CANONICAL_SECTION_TITLES[lower]
    if "FINAL" in upper and ("DIAGNOS" in upper or "DYAGNOS" in upper):
        return "Final Diagnosis"
    if "FINAL DIAGNOSIS" in upper or upper.startswith("PATH FINAL DIAGNOSIS"):
        return "Final Diagnosis"
    if "DIAGNOSIS" in upper or "NAL DIAGNOSIS" in upper:
        return "Diagnosis"
    if "GROSS DESCRIPTION" in upper:
        return "Gross Description"
    if "MICROSCOPIC DESCRIPTION" in upper:
        return "Microscopic Description"
    if "CLINICAL NOTE" in upper or "CLINICAL INFORMATION" in upper:
        return "Clinical Information"
    if upper.startswith("SPECIMEN"):
        return "Specimen Submitted"
    if "CHECKLIST" in upper or "SYNOPTIC" in upper or "CONSOLIDATED DIAGNOSTIC PATHOLOGY FORM" in upper:
        return "Synoptic Report"
    if "SUMMARY OF SECTIONS" in upper:
        return "Summary of Sections"
    if "INTRAOPERATIVE CONSULTATION" in upper:
        return "Intraoperative Consultation"
    if "ANCILLARY STUDIES" in upper:
        return "Ancillary Studies"
    if "HER2" in upper:
        return "Ancillary Studies"
    if "PATIENT HISTORY" in upper:
        return "Patient History"
    if "PROCEDURE" in upper:
        return "Procedure"
    if "COMMENT" in upper:
        return "Comment"
    if ("PATHO" in upper or "PATRFOLOGY" in upper or "PLOGY" in upper) and "REPORT" in upper:
        return "Document Body"
    if "TCGA-" in upper or re.search(r"\b\d{2,}[A-Z-]*\b", upper):
        return "Document Body"
    if upper.startswith("PAGE ") or upper.startswith("PACE "):
        return "Document Body"
    if "SURGICAL PATHOLOGY" in upper and "DIAGNOSIS" not in upper:
        return "Document Body"
    if upper in {"MRN", "MR #", "NAME", "KARYOTYPE", "I", "J", "E", "B", "SPECIMEN"}:
        return "Document Body"
    if re.fullmatch(r"[A-Z]", upper):
        return "Document Body"
    if re.fullmatch(r"[A-Z0-9#/\\-]{1,8}", upper):
        return "Document Body"
    if alpha_count <= 4 and (digit_count > 0 or weird_count > 0):
        return "Document Body"
    if weird_count >= 2 and digit_count >= 1:
        return "Document Body"
    return title


def infer_source_paths(payload: dict, metadata_json_path: Path, input_root: Path) -> tuple[str | None, str | None]:
    relative_path = metadata_json_path.relative_to(input_root)
    output_root = input_root.parent
    sentence_view_path = output_root / "sentence_exports_masked" / relative_path

    source_sentence_view_json = str(sentence_view_path) if sentence_view_path.exists() else payload.get("source_sentence_view_json")
    source_preprocessed_json = payload.get("source_preprocessed_json") or payload.get("source_sentence_json")

    if sentence_view_path.exists():
        try:
            sentence_view_payload = load_json(sentence_view_path)
            source_preprocessed_json = sentence_view_payload.get("source_json") or source_preprocessed_json
        except Exception:
            pass

    if source_preprocessed_json:
        preprocessed_path = Path(source_preprocessed_json)
        if not preprocessed_path.exists():
            parts = list(preprocessed_path.parts)
            for folder_name in (
                "pathology_report_preprocessed_masked",
                "pathology_report_preprocessed_no_diagnosis",
                "pathology_report_preprocessed_no_diagnosis_masked",
                "pathology_report_preprocessed_full",
            ):
                if folder_name in parts:
                    idx = parts.index(folder_name)
                    candidate = output_root.joinpath(*parts[idx:])
                    if candidate.exists():
                        source_preprocessed_json = str(candidate)
                        break

    return source_sentence_view_json, source_preprocessed_json


def clean_payload(payload: dict, metadata_json_path: Path, input_root: Path) -> dict:
    cleaned = dict(payload)
    source_sentence_view_json, source_preprocessed_json = infer_source_paths(
        payload=payload,
        metadata_json_path=metadata_json_path,
        input_root=input_root,
    )
    cleaned["source_sentence_view_json"] = source_sentence_view_json
    cleaned["source_preprocessed_json"] = source_preprocessed_json

    raw_sections = sorted(payload.get("sections", []), key=lambda item: int(item.get("section_index", 0)))
    raw_sentence_records = sorted(payload.get("sentence_records", []), key=lambda item: int(item.get("sentence_index", 0)))
    sentence_record_map = {
        int(record.get("sentence_index", index)): record
        for index, record in enumerate(raw_sentence_records)
    }

    merged_sections: list[dict] = []
    cleaned_sentence_records: list[dict] = []
    sentence_to_section: list[int] = []
    renamed_section_count = 0
    merged_section_count = 0

    for raw_section in raw_sections:
        start = int(raw_section.get("sentence_start", 0))
        end = int(raw_section.get("sentence_end", start))
        if end <= start:
            continue

        original_title = str(raw_section.get("section_title", "Document Body"))
        normalized_title = normalize_section_title(original_title)
        if normalized_title != original_title:
            renamed_section_count += 1

        if (
            merged_sections
            and merged_sections[-1]["section_title"] == normalized_title
            and int(merged_sections[-1]["sentence_end"]) == start
        ):
            section_index = int(merged_sections[-1]["section_index"])
            merged_sections[-1]["sentence_end"] = end
            merged_sections[-1]["sentence_count"] = end - int(merged_sections[-1]["sentence_start"])
            merged_section_count += 1
        else:
            section_index = len(merged_sections)
            merged_sections.append(
                {
                    "section_index": section_index,
                    "section_title": normalized_title,
                    "sentence_start": start,
                    "sentence_end": end,
                    "sentence_count": end - start,
                }
            )

        section_start = int(merged_sections[section_index]["sentence_start"])
        for sentence_index in range(start, end):
            record = dict(sentence_record_map.get(sentence_index, {}))
            record["sentence_index"] = sentence_index
            record["section_index"] = section_index
            record["section_title"] = normalized_title
            record["section_sentence_index"] = sentence_index - section_start
            cleaned_sentence_records.append(record)
            sentence_to_section.append(section_index)

    cleaned["sections"] = merged_sections
    cleaned["sentence_records"] = cleaned_sentence_records
    cleaned["sentence_to_section"] = sentence_to_section
    cleaned["section_count"] = len(merged_sections)
    cleaned["sentence_count"] = len(cleaned_sentence_records)
    cleaned["graph_cleanup"] = {
        "original_section_count": len(raw_sections),
        "cleaned_section_count": len(merged_sections),
        "renamed_section_count": renamed_section_count,
        "merged_section_count": merged_section_count,
    }
    return cleaned


def mean_pool(features: torch.Tensor) -> torch.Tensor:
    if features.numel() == 0:
        return torch.zeros(FEATURE_DIM, dtype=torch.float32)
    return features.mean(dim=0)


def validate_payload(payload: dict, sentence_features: torch.Tensor) -> None:
    sentence_count = int(payload.get("sentence_count", 0))
    if sentence_features.ndim != 2:
        raise ValueError(f"Expected sentence feature tensor to be 2D, got shape {tuple(sentence_features.shape)}")
    if sentence_features.shape[1] != FEATURE_DIM:
        raise ValueError(f"Expected feature dim {FEATURE_DIM}, got {sentence_features.shape[1]}")
    if sentence_features.shape[0] != sentence_count:
        raise ValueError(
            f"Sentence count mismatch: metadata has {sentence_count}, tensor has {sentence_features.shape[0]}"
        )


def build_section_features(payload: dict, sentence_features: torch.Tensor) -> torch.Tensor:
    pooled: list[torch.Tensor] = []
    for section in payload.get("sections", []):
        start = int(section["sentence_start"])
        end = int(section["sentence_end"])
        pooled.append(mean_pool(sentence_features[start:end]))
    if not pooled:
        return torch.empty((0, FEATURE_DIM), dtype=torch.float32)
    return torch.stack(pooled, dim=0).float()


def build_document_feature(section_features: torch.Tensor, sentence_features: torch.Tensor) -> torch.Tensor:
    if section_features.numel() > 0:
        return mean_pool(section_features).float()
    return mean_pool(sentence_features).float()


def build_nodes(payload: dict) -> tuple[list[dict], list[int], list[int]]:
    nodes: list[dict] = []
    section_node_indices: list[int] = []
    sentence_node_indices: list[int] = []

    nodes.append(
        {
            "node_index": 0,
            "node_id": "doc_0",
            "node_type": "document",
            "title": payload.get("document_id") or payload.get("file_name") or "document",
            "level": 0,
        }
    )

    for section in payload.get("sections", []):
        node_index = len(nodes)
        section_index = int(section["section_index"])
        section_node_indices.append(node_index)
        nodes.append(
            {
                "node_index": node_index,
                "node_id": f"sec_{section_index}",
                "node_type": "section",
                "level": 1,
                "section_index": section_index,
                "section_title": section["section_title"],
                "sentence_start": int(section["sentence_start"]),
                "sentence_end": int(section["sentence_end"]),
                "sentence_count": int(section["sentence_count"]),
            }
        )

    for record in payload.get("sentence_records", []):
        node_index = len(nodes)
        sentence_index = int(record["sentence_index"])
        sentence_node_indices.append(node_index)
        nodes.append(
            {
                "node_index": node_index,
                "node_id": f"sent_{sentence_index}",
                "node_type": "sentence",
                "level": 2,
                "sentence_index": sentence_index,
                "section_index": int(record["section_index"]),
                "section_title": record["section_title"],
                "section_sentence_index": int(record["section_sentence_index"]),
                "text": record["text"],
            }
        )

    return nodes, section_node_indices, sentence_node_indices


def build_edges(
    payload: dict,
    section_node_indices: list[int],
    sentence_node_indices: list[int],
) -> list[dict]:
    edges: list[dict] = []

    # Parent edges: document -> section
    for section_index, section_node_index in enumerate(section_node_indices):
        edges.append(
            {
                "source_index": 0,
                "target_index": section_node_index,
                "edge_type": "parent",
                "source_type": "document",
                "target_type": "section",
                "section_index": section_index,
            }
        )

    # Parent edges: section -> sentence
    sentence_to_section = payload.get("sentence_to_section", [])
    for sentence_index, section_index in enumerate(sentence_to_section):
        section_index = int(section_index)
        sentence_node_index = sentence_node_indices[sentence_index]
        edges.append(
            {
                "source_index": section_node_indices[section_index],
                "target_index": sentence_node_index,
                "edge_type": "parent",
                "source_type": "section",
                "target_type": "sentence",
                "section_index": section_index,
                "sentence_index": sentence_index,
            }
        )

    # Next edges: section order
    for i in range(len(section_node_indices) - 1):
        edges.append(
            {
                "source_index": section_node_indices[i],
                "target_index": section_node_indices[i + 1],
                "edge_type": "next",
                "source_type": "section",
                "target_type": "section",
            }
        )

    # Next edges: sentence order across full document
    for i in range(len(sentence_node_indices) - 1):
        edges.append(
            {
                "source_index": sentence_node_indices[i],
                "target_index": sentence_node_indices[i + 1],
                "edge_type": "next",
                "source_type": "sentence",
                "target_type": "sentence",
            }
        )

    return edges


def build_edge_tensors(edges: list[dict]) -> tuple[torch.Tensor, torch.Tensor]:
    if not edges:
        return (
            torch.empty((2, 0), dtype=torch.long),
            torch.empty((0,), dtype=torch.long),
        )
    edge_index = torch.tensor(
        [[int(edge["source_index"]) for edge in edges], [int(edge["target_index"]) for edge in edges]],
        dtype=torch.long,
    )
    edge_type = torch.tensor([EDGE_TYPE_TO_ID[edge["edge_type"]] for edge in edges], dtype=torch.long)
    return edge_index, edge_type


def build_node_feature_matrix(
    document_feature: torch.Tensor,
    section_features: torch.Tensor,
    sentence_features: torch.Tensor,
) -> torch.Tensor:
    pieces = [document_feature.view(1, -1).float()]
    if section_features.numel() > 0:
        pieces.append(section_features.float())
    if sentence_features.numel() > 0:
        pieces.append(sentence_features.float())
    return torch.cat(pieces, dim=0)


def build_node_type_tensor(section_count: int, sentence_count: int) -> torch.Tensor:
    node_types = [NODE_TYPE_TO_ID["document"]]
    node_types.extend([NODE_TYPE_TO_ID["section"]] * section_count)
    node_types.extend([NODE_TYPE_TO_ID["sentence"]] * sentence_count)
    return torch.tensor(node_types, dtype=torch.long)


def build_graph_payload(payload: dict, sentence_features: torch.Tensor) -> tuple[dict, dict]:
    validate_payload(payload, sentence_features)

    section_features = build_section_features(payload, sentence_features)
    document_feature = build_document_feature(section_features, sentence_features)

    nodes, section_node_indices, sentence_node_indices = build_nodes(payload)
    edges = build_edges(payload, section_node_indices=section_node_indices, sentence_node_indices=sentence_node_indices)
    edge_index, edge_type = build_edge_tensors(edges)

    node_features = build_node_feature_matrix(
        document_feature=document_feature,
        section_features=section_features,
        sentence_features=sentence_features,
    )
    node_type = build_node_type_tensor(
        section_count=section_features.shape[0],
        sentence_count=sentence_features.shape[0],
    )

    graph_tensor_payload = {
        "document_feature": document_feature.float(),
        "section_features": section_features.float(),
        "sentence_features": sentence_features.float(),
        "node_features": node_features.float(),
        "node_type": node_type,
        "edge_index": edge_index,
        "edge_type": edge_type,
        "sentence_to_section": torch.tensor(payload.get("sentence_to_section", []), dtype=torch.long),
        "section_spans": torch.tensor(
            [[int(section["sentence_start"]), int(section["sentence_end"])] for section in payload.get("sections", [])],
            dtype=torch.long,
        )
        if payload.get("sections")
        else torch.empty((0, 2), dtype=torch.long),
        "node_type_mapping": NODE_TYPE_TO_ID,
        "edge_type_mapping": EDGE_TYPE_TO_ID,
    }

    graph_json_payload = {
        "document_id": payload.get("document_id"),
        "file_name": payload.get("file_name"),
        "dataset": payload.get("dataset"),
        "filter_mode": payload.get("filter_mode"),
        "source_pdf": payload.get("source_pdf"),
        "source_sentence_view_json": payload.get("source_sentence_view_json"),
        "source_preprocessed_json": payload.get("source_preprocessed_json") or payload.get("source_sentence_json"),
        "embedding_path": payload.get("embedding_path"),
        "pooling": "mean",
        "feature_dim": FEATURE_DIM,
        "graph_cleanup": payload.get("graph_cleanup", {}),
        "node_type_mapping": NODE_TYPE_TO_ID,
        "edge_type_mapping": EDGE_TYPE_TO_ID,
        "node_count": len(nodes),
        "edge_count": len(edges),
        "node_counts": {
            "document": 1,
            "section": int(section_features.shape[0]),
            "sentence": int(sentence_features.shape[0]),
        },
        "nodes": nodes,
        "edges": edges,
    }
    return graph_tensor_payload, graph_json_payload


def build_graph_for_document(
    metadata_json_path: Path,
    input_root: Path,
    output_root: Path,
) -> dict:
    payload = clean_payload(load_json(metadata_json_path), metadata_json_path=metadata_json_path, input_root=input_root)
    relative_path = metadata_json_path.relative_to(input_root)
    output_json_path = output_root / relative_path
    output_pt_path = output_root / relative_path.with_suffix(".pt")
    ensure_dir(output_json_path.parent)

    embedding_path = metadata_json_path.with_suffix(".pt")
    if not embedding_path.exists():
        embedding_path = Path(payload["embedding_path"])
    payload["embedding_path"] = str(embedding_path)
    sentence_features = torch.load(embedding_path, map_location="cpu")

    if int(payload.get("sentence_count", 0)) == 0:
        if output_json_path.exists():
            output_json_path.unlink()
        if output_pt_path.exists():
            output_pt_path.unlink()
        return {
            "document_id": payload.get("document_id"),
            "file_name": payload.get("file_name"),
            "dataset": payload.get("dataset"),
            "source_embedding_json": str(metadata_json_path),
            "source_embedding_pt": str(embedding_path),
            "output_graph_json": None,
            "output_graph_pt": None,
            "node_count": 0,
            "edge_count": 0,
            "sentence_count": 0,
            "section_count": 0,
            "status": "skipped",
            "skip_reason": "empty_graph_after_cleanup",
            "graph_cleanup": payload.get("graph_cleanup", {}),
        }

    graph_tensor_payload, graph_json_payload = build_graph_payload(payload, sentence_features=sentence_features)

    torch.save(graph_tensor_payload, output_pt_path)
    graph_json_payload["graph_tensor_path"] = str(output_pt_path)
    write_json(output_json_path, graph_json_payload)

    return {
        "document_id": payload.get("document_id"),
        "file_name": payload.get("file_name"),
        "dataset": payload.get("dataset"),
        "source_embedding_json": str(metadata_json_path),
        "source_embedding_pt": str(embedding_path),
        "output_graph_json": str(output_json_path),
        "output_graph_pt": str(output_pt_path),
        "node_count": graph_json_payload["node_count"],
        "edge_count": graph_json_payload["edge_count"],
        "sentence_count": graph_json_payload["node_counts"]["sentence"],
        "section_count": graph_json_payload["node_counts"]["section"],
        "status": "success",
        "graph_cleanup": payload.get("graph_cleanup", {}),
    }


def process_all_documents(input_dir: Path, output_dir: Path, limit: int | None) -> dict:
    input_root = Path(input_dir)
    output_root = Path(output_dir)
    ensure_dir(output_root)

    log_path = output_root / "graph.log"
    root_logger = logging.getLogger()
    for handler in list(root_logger.handlers):
        root_logger.removeHandler(handler)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        handlers=[
            logging.FileHandler(log_path, encoding="utf-8"),
            logging.StreamHandler(),
        ],
    )

    metadata_paths = iter_metadata_jsons(input_root)
    if limit is not None:
        metadata_paths = metadata_paths[:limit]

    LOGGER.info("Discovered %s embedding metadata JSON files under %s", len(metadata_paths), input_root)

    summaries: list[dict] = []
    for index, metadata_json_path in enumerate(metadata_paths, start=1):
        LOGGER.info("[%s/%s] Building graph for %s", index, len(metadata_paths), metadata_json_path)
        try:
            summary = build_graph_for_document(
                metadata_json_path=metadata_json_path,
                input_root=input_root,
                output_root=output_root,
            )
        except Exception as exc:
            LOGGER.exception("Failed to build graph for %s", metadata_json_path)
            summary = {
                "document_id": metadata_json_path.stem,
                "file_name": metadata_json_path.name,
                "dataset": None,
                "source_embedding_json": str(metadata_json_path),
                "source_embedding_pt": None,
                "output_graph_json": None,
                "output_graph_pt": None,
                "node_count": 0,
                "edge_count": 0,
                "sentence_count": 0,
                "section_count": 0,
                "status": "failed",
                "error": str(exc),
            }
        summaries.append(summary)

    successes = [item for item in summaries if item["status"] == "success"]
    failures = [item for item in summaries if item["status"] == "failed"]
    skipped = [item for item in summaries if item["status"] == "skipped"]

    dataset_counts: dict[str, int] = {}
    for item in successes:
        dataset = item.get("dataset") or "UNKNOWN"
        dataset_counts[dataset] = dataset_counts.get(dataset, 0) + 1

    run_summary = {
        "input_dir": str(input_root),
        "output_dir": str(output_root),
        "pooling": "mean",
        "feature_dim": FEATURE_DIM,
        "graph_schema": {
            "node_levels": ["document", "section", "sentence"],
            "edge_types": ["parent", "next"],
        },
        "total_metadata_files": len(metadata_paths),
        "success_count": len(successes),
        "skipped_count": len(skipped),
        "failure_count": len(failures),
        "datasets": dataset_counts,
        "files": summaries,
    }
    write_json(output_root / "run_summary.json", run_summary)
    LOGGER.info(
        "Completed graph build | total=%s | success=%s | skipped=%s | failed=%s",
        len(metadata_paths),
        len(successes),
        len(skipped),
        len(failures),
    )
    return run_summary


def parse_args() -> argparse.Namespace:
    pre_parser = argparse.ArgumentParser(add_help=False)
    pre_parser.add_argument("--config", type=Path, default=None, help="Optional YAML config preset.")
    pre_args, _ = pre_parser.parse_known_args()
    raw_config, config_path = load_yaml_config(pre_args.config)
    stage_block = raw_config.get("build_text_hierarchy_graphs") if isinstance(raw_config.get("build_text_hierarchy_graphs"), dict) else {}
    config = get_stage_config(raw_config, "build_text_hierarchy_graphs")
    defaults_block = raw_config.get("defaults") if isinstance(raw_config.get("defaults"), dict) else {}
    preprocess_config = get_stage_config(raw_config, "preprocess")
    filter_mode = str(get_value(preprocess_config, "filter_mode", "masked"))
    output_root = get_path(defaults_block, "output_root", DEFAULT_OUTPUT_ROOT, config_path)

    input_default = get_path(stage_block, "input_dir", DEFAULT_INPUT_DIR, config_path)
    output_default = get_path(stage_block, "output_dir", DEFAULT_OUTPUT_DIR, config_path)

    if stage_block:
        if stage_block.get("input_dir") in (None, ""):
            conch_output_subdirs = dict(DEFAULT_CONCH_OUTPUT_SUBDIRS)
            conch_output_subdirs.update(get_value(get_stage_config(raw_config, "encode_sentence_exports_conch"), "output_subdirs", {}) or {})
            input_default = output_root / conch_output_subdirs.get(filter_mode, DEFAULT_CONCH_OUTPUT_SUBDIRS["masked"])
        if stage_block.get("output_dir") in (None, ""):
            graph_output_subdirs = dict(DEFAULT_GRAPH_OUTPUT_SUBDIRS)
            graph_output_subdirs.update(get_value(config, "output_subdirs", {}) or {})
            output_default = output_root / graph_output_subdirs.get(filter_mode, DEFAULT_GRAPH_OUTPUT_SUBDIRS["masked"])

    parser = argparse.ArgumentParser(
        description="Build Document -> Section -> Sentence hierarchy graphs from sentence-level CONCH embeddings."
    )
    parser.add_argument("--config", type=Path, default=pre_args.config, help="Optional YAML config preset.")
    parser.add_argument(
        "--input_dir",
        type=Path,
        default=input_default,
        help="Directory containing embedding metadata JSON files.",
    )
    parser.add_argument(
        "--output_dir",
        type=Path,
        default=output_default,
        help="Directory for hierarchy graph outputs.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None if get_value(config, "limit", None) is None else int(get_value(config, "limit", None)),
        help="Optional cap on number of documents to convert.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    summary = process_all_documents(
        input_dir=args.input_dir,
        output_dir=args.output_dir,
        limit=args.limit,
    )
    print(
        f"Built graphs for {summary['total_metadata_files']} files | success={summary['success_count']} | "
        f"failed={summary['failure_count']}"
    )


if __name__ == "__main__":
    main()
